# Pull base image
From tomcat:7-jre8

# Maintainer
MAINTAINER "dede <xxx@gmail.com">

# Copy to images tomcat path
#ADD /home/hackathon/Téléchargements/containerbank-master/target/containerbank.war /usr/local/tomcat/webapps/
ADD containerbank.war /usr/local/tomcat/webapps/
