---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: packapp02-dd-disk
  namespace: packapp02
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      team: packapp03
  resources:
    requests:
      storage: 2Gi

